/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c2fb24ed6eb6ba73665d1a00f572f3f7)
interface __BaseEnv_Env {
	F: R2Bucket;
	ASSETS: Fetcher;
	PAYSTACK_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
